# coding: utf-8

"""
    UltraScan 3 LIMS Database Instance API

    A more machine-accessible version of the UltraScan 3 LIMS functionality. The authentication is done using the user's US3 LIMS credentials and sending them with every request as header `Us-Email` and `Us-Password`. Alternatively Basic Auth can be used.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501
import json
import unittest

from us3api.models.global_type import GlobalType

class TestGlobalType(unittest.TestCase):
    """GlobalType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass
    
    def test_enum_values(self):
        self.assertEqual(GlobalType.NORMAL, 'NORMAL')
        self.assertEqual(GlobalType.MENISCUS, 'MENISCUS')
        self.assertEqual(GlobalType.GLOBAL, 'GLOBAL')
        self.assertEqual(GlobalType.SUPERGLOBAL, 'SUPERGLOBAL')
    
    def test_from_json(self):
        test_json = json.dumps('GLOBAL')
        result = GlobalType.from_json(test_json)
        self.assertEqual(result, GlobalType.GLOBAL)
        
        test_json = json.dumps('NORMAL')
        result = GlobalType.from_json(test_json)
        self.assertEqual(result, GlobalType.NORMAL)
        
        test_json = json.dumps('MENISCUS')
        result = GlobalType.from_json(test_json)
        self.assertEqual(result, GlobalType.MENISCUS)
        
        test_json = json.dumps('SUPERGLOBAL')
        result = GlobalType.from_json(test_json)
        self.assertEqual(result, GlobalType.SUPERGLOBAL)
        
        test_invalid_json = json.dumps('INVALID')
        with self.assertRaises(ValueError):
            GlobalType.from_json(test_invalid_json)

if __name__ == '__main__':
    unittest.main()
