# coding: utf-8

"""
    UltraScan 3 LIMS Database Instance API

    A more machine-accessible version of the UltraScan 3 LIMS functionality. The authentication is done using the user's US3 LIMS credentials and sending them with every request as header `Us-Email` and `Us-Password`. Alternatively Basic Auth can be used.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

import us3api
from us3api.models.person import Person

class TestPerson(unittest.TestCase):
    """Person unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Person:
        """Test Person
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Person`
        if include_optional:
            return Person(
                person_id = 56,
                person_guid = '',
                email = '',
                first_name = '',
                last_name = '',
                activated = True,
                username = '',
                advanced_level = True,
                user_level = 56,
                cluster_authorizations = '',
                cluster_nodes = [
                    us3api.models.cluster_node.ClusterNode(
                        name = '', 
                        explicit_name = '', 
                        short_name = '', 
                        queue = '', )
                    ]
            )
        else:
            return Person(
                person_id = 56,
                person_guid = '',
                email = '',
                first_name = '',
                last_name = '',
                activated = True,
        )


    def testPerson(self):
        """Test Person"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
