# coding: utf-8

"""
    UltraScan 3 LIMS Database Instance API

    A more machine-accessible version of the UltraScan 3 LIMS functionality. The authentication is done using the user's US3 LIMS credentials and sending them with every request as header `Us-Email` and `Us-Password`. Alternatively Basic Auth can be used.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from us3api.models.hpc_job_data_set_data import HPCJobDataSetData

class TestHPCJobDataSetData(unittest.TestCase):
    """HPCJobDataSetData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HPCJobDataSetData:
        """Test HPCJobDataSetData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HPCJobDataSetData`
        if include_optional:
            return HPCJobDataSetData(
                edit_id = 56,
                raw_data_id = 56,
                ri_noise = 56,
                ti_noise = 56,
                simpoints = 56,
                band_volume = 1.337,
                radial_grid = 'ASTFEM',
                time_grid = 'AST'
            )
        else:
            return HPCJobDataSetData(
        )


    def testHPCJobDataSetData(self):
        """Test HPCJobDataSetData"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
