# coding: utf-8

"""
    UltraScan 3 LIMS Database Instance API

    A more machine-accessible version of the UltraScan 3 LIMS functionality. The authentication is done using the user's US3 LIMS credentials and sending them with every request as header `Us-Email` and `Us-Password`. Alternatively Basic Auth can be used.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from us3api.models.noise import Noise
from typing import Optional, Set
from typing_extensions import Self

class EditedData(BaseModel):
    """
    EditedData
    """ # noqa: E501
    edited_data_id: StrictInt = Field(alias="editedDataID")
    raw_data_id: Optional[StrictInt] = Field(default=None, alias="rawDataID")
    edit_guid: Optional[StrictStr] = Field(default=None, alias="editGUID")
    label: Optional[StrictStr] = None
    filename: Optional[StrictStr] = None
    comment: Optional[StrictStr] = None
    last_updated: Optional[datetime] = Field(default=None, alias="lastUpdated")
    models: Optional[List[Model]] = Field(default=None, description="The models for this edit. For each model only the modelID, description and globalType are returned")
    latest_noises: Optional[Annotated[List[Noise], Field(max_length=2)]] = Field(default=None, description="The latest noise data for this edit")
    hp_crequest_id: Optional[StrictInt] = Field(default=None, description="The latest HPC request for this edit", alias="HPCrequestID")
    __properties: ClassVar[List[str]] = ["editedDataID", "rawDataID", "editGUID", "label", "filename", "comment", "lastUpdated", "models", "latest_noises", "HPCrequestID"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EditedData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in models (list)
        _items = []
        if self.models:
            for _item in self.models:
                if _item:
                    _items.append(_item.to_dict())
            _dict['models'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in latest_noises (list)
        _items = []
        if self.latest_noises:
            for _item in self.latest_noises:
                if _item:
                    _items.append(_item.to_dict())
            _dict['latest_noises'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EditedData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "editedDataID": obj.get("editedDataID"),
            "rawDataID": obj.get("rawDataID"),
            "editGUID": obj.get("editGUID"),
            "label": obj.get("label"),
            "filename": obj.get("filename"),
            "comment": obj.get("comment"),
            "lastUpdated": obj.get("lastUpdated"),
            "models": [Model.from_dict(_item) for _item in obj["models"]] if obj.get("models") is not None else None,
            "latest_noises": [Noise.from_dict(_item) for _item in obj["latest_noises"]] if obj.get("latest_noises") is not None else None,
            "HPCrequestID": obj.get("HPCrequestID")
        })
        return _obj

from us3api.models.model import Model
# TODO: Rewrite to not use raise_errors
EditedData.model_rebuild(raise_errors=False)

