# coding: utf-8

"""
    UltraScan 3 LIMS Database Instance API

    A more machine-accessible version of the UltraScan 3 LIMS functionality. The authentication is done using the user's US3 LIMS credentials and sending them with every request as header `Us-Email` and `Us-Password`. Alternatively Basic Auth can be used.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class HPCAnalysisMethod(str, Enum):
    """
    HPCAnalysisMethod
    """

    """
    allowed enum values
    """
    ENUM_2_DSA = '2DSA'
    ENUM_2_DSA_CG = '2DSA_CG'
    ENUM_2_DSA_MW = '2DSA_MW'
    GA = 'GA'
    GA_MW = 'GA_MW'
    GA_SC = 'GA_SC'
    DMGA = 'DMGA'
    PCSA = 'PCSA'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of HPCAnalysisMethod from a JSON string"""
        return cls(json.loads(json_str))


