# coding: utf-8

"""
    UltraScan 3 LIMS Database Instance API

    A more machine-accessible version of the UltraScan 3 LIMS functionality. The authentication is done using the user's US3 LIMS credentials and sending them with every request as header `Us-Email` and `Us-Password`. Alternatively Basic Auth can be used.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from us3api.models.edited_data import EditedData
from typing import Optional, Set
from typing_extensions import Self

class RawData(BaseModel):
    """
    RawData
    """ # noqa: E501
    raw_data_id: StrictInt = Field(alias="rawDataID")
    label: StrictStr
    filename: StrictStr
    comment: Optional[StrictStr] = None
    solution_id: Optional[StrictInt] = Field(default=None, alias="solutionID")
    experiment_id: Optional[StrictInt] = Field(default=None, alias="experimentID")
    run_id: Optional[StrictStr] = Field(default=None, alias="runID")
    last_updated: Optional[StrictStr] = Field(default=None, alias="lastUpdated")
    description: Optional[StrictStr] = None
    edits: Optional[List[EditedData]] = None
    __properties: ClassVar[List[str]] = ["rawDataID", "label", "filename", "comment", "solutionID", "experimentID", "runID", "lastUpdated", "description", "edits"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RawData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in edits (list)
        _items = []
        if self.edits:
            for _item in self.edits:
                if _item:
                    _items.append(_item.to_dict())
            _dict['edits'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RawData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "rawDataID": obj.get("rawDataID"),
            "label": obj.get("label"),
            "filename": obj.get("filename"),
            "comment": obj.get("comment"),
            "solutionID": obj.get("solutionID"),
            "experimentID": obj.get("experimentID"),
            "runID": obj.get("runID"),
            "lastUpdated": obj.get("lastUpdated"),
            "description": obj.get("description"),
            "edits": [EditedData.from_dict(_item) for _item in obj["edits"]] if obj.get("edits") is not None else None
        })
        return _obj


